ingress:
  enabled: true

  # EG:
  # TODO: annotations must be empty on default.. configuration must be added only when required
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: "true"
  path: /
  hosts:
    - stewart.deltashim.com
  tls:
   - secretName: acme-stewart.deltashim.com
     hosts:
       - stewart.deltashim.com


# set config.yaml (will be given to the server) from here..
config:
  # List of agents that are allowed to communicate with tokenSecured endpoints
  agents:
      # insert the token that it generated
    - token: 898cc114-1a28-4664-8b30-015bdde089bf
      # give it a name.. you'll need this later
      name: deltashim

  # ordering probably matters to you... set that here
  # Notice the example includes two "demo" lanes..
  # This is for the make-believe situation of having
  # similar "environments" but wanting to group them
  # differently
  lane_order:

    - id: any
      agents:
        - deltashim

prometheus:
  enabled: false
